export { default as Portfolio } from './pages/Portfolio'
export { default as About } from './pages/About'
export { default as Contact } from './pages/Contact'
export { default as Motion } from './pages/Motion'
export { default as InTheKitchen } from './pages/InTheKitchen'